In [1]:
?matrix
matrix

function (data = NA, nrow = 1, ncol = 1, byrow = FALSE, dimnames = NULL) 
{
    if (is.object(data) || !is.atomic(data)) 
        data <- as.vector(data)
    .Internal(matrix(data, nrow, ncol, byrow, dimnames, missing(nrow), 
        missing(ncol)))
}
<bytecode: 0x00000000273a0c08>
<environment: namespace:base>

In [2]:
matrix()
matrix(nrow=2, ncol=3)
matrix(0, 2, 3)
matrix(1:6, 2, 3)
matrix(1:6, 2, 3, byrow=TRUE)

[,1]
[1,] NA

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 0    0    0

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [3]:
#row names and column names
rnames <- c('R1', 'R2')
cnames <- c('C1', 'C2', 'C3')
matrix(1:6, nrow=2, dimnames=list(rnames, cnames))

C1 C2 C3
R1 1  3  5 
R2 2  4  6

In [4]:
#assign row names and column names
x=matrix(1:6, nrow=2)
rownames(x)=c('r1', 'r2')
colnames(x)=c('c1', 'c2', 'c3')
x

c1 c2 c3
r1 1  3  5 
r2 2  4  6

In [5]:
#use dim() to create matrix from vector
x <- 1:6   ##vector
x
dim(x) <- c(3, 2)  ##convert vector to matrix in place
is.matrix(x)   
x 

[1] 1 2 3 4 5 6

[1] TRUE

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [6]:
#Matrix Transpose
?t
t(x)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [7]:
#matrix attributes
rnames <- c('R1', 'R2')
cnames <- c('C1', 'C2', 'C3')
x=matrix(1:6, nrow=2, dimnames=list(rnames, cnames))
x
class(x)  ##data structure type
typeof(x)  ##element data type
dim(x)  ##dimension
length(x)  ##total number of elements
rownames(x)  ##get row names
colnames(x)  ##get column names

C1 C2 C3
R1 1  3  5 
R2 2  4  6

[1] "matrix"

[1] "integer"

[1] 2 3

[1] 6

[1] "R1" "R2"

[1] "C1" "C2" "C3"

In [8]:
#bind vectors into matrix
rbind(c(71,172),c(73,169),c(69,160),c(65,130))
cbind(c(71,73,69,65),c(172,169,160,130))

[,1] [,2]
[1,] 71   172 
[2,] 73   169 
[3,] 69   160 
[4,] 65   130

[,1] [,2]
[1,] 71   172 
[2,] 73   169 
[3,] 69   160 
[4,] 65   130

In [9]:
#access elements in matrix
x
x[,2]
x[2,]
x[2,2]

C1 C2 C3
R1 1  3  5 
R2 2  4  6

R1 R2 
 3  4

C1 C2 C3 
 2  4  6

[1] 4

In [10]:
typeof(x[2,])
class(x[2,])
x[2,][1]

[1] "integer"

[1] "integer"

C1 
 2

In [11]:
x[,c(1,2)]
x[c(1,2),]

C1 C2
R1 1  3 
R2 2  4

C1 C2 C3
R1 1  3  5 
R2 2  4  6

In [12]:
x[,c(2:3)]
x[1,c(2:3)]

C2 C3
R1 3  5 
R2 4  6

C2 C3 
 3  5

In [13]:
x[,-c(2:3)] #exclude

R1 R2 
 1  2

In [14]:
# how does R deal with incomplete data. Cyclically reuse the vector.
x=rbind(c(71,172),c(73),c(69,160),c(65,130)); x
y=cbind(c(71,73,65),c(172,169,160,130)); y
y=cbind(c(71,73,69,65),c(172,169,130)); y

[,1] [,2]
[1,] 71   172 
[2,] 73    73 
[3,] 69   160 
[4,] 65   130

Warning message in cbind(c(71, 73, 65), c(172, 169, 160, 130)):
"number of rows of result is not a multiple of vector length (arg 1)"

[,1] [,2]
[1,] 71   172 
[2,] 73   169 
[3,] 65   160 
[4,] 71   130

Warning message in cbind(c(71, 73, 69, 65), c(172, 169, 130)):
"number of rows of result is not a multiple of vector length (arg 2)"

[,1] [,2]
[1,] 71   172 
[2,] 73   169 
[3,] 69   130 
[4,] 65   172

In [15]:
# how does R deal with incomplete data. Cyclically reuse the vector.
z=matrix(1:6,2,5); z
z=matrix(1:6,2,5, byrow=T); z

Warning message in matrix(1:6, 2, 5):
"data length [6] is not a sub-multiple or multiple of the number of columns [5]"

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    1    3   
[2,] 2    4    6    2    4

Warning message in matrix(1:6, 2, 5, byrow = T):
"data length [6] is not a sub-multiple or multiple of the number of columns [5]"

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4    5   
[2,] 6    1    2    3    4

In [16]:
x=c(1,2,3,4,5,6);x
x[1] #index starts from 1
x[2]
x[0] # it is always integer(0) or numeric(0)
print(x[0])
x[2:3] #slicing
x[-2] #drop
x[c(3,5,6)]
x[c(3,5,6,8)] #when index is out of range

[1] 1 2 3 4 5 6

[1] 1

[1] 2

numeric(0)

numeric(0)


[1] 2 3

[1] 1 3 4 5 6

[1] 3 5 6

[1]  3  5  6 NA

In [17]:
#filtering
x[x>3]
x[x<2 | x>3]
which(x>3)  #return indices
which(x<2 | x>3)
which.max(x)
y=c(2,3,3,2)
which.max(y)
?which.max

[1] 4 5 6

[1] 1 4 5 6

[1] 4 5 6

[1] 1 4 5 6

[1] 6

[1] 2

In [18]:
# logical vectors
x
x>3
x<2 | x>3  
x<2 & x>3  
all(x>3)
any(x>3)
x %in% c(2,4)

[1] 1 2 3 4 5 6

[1] FALSE FALSE FALSE  TRUE  TRUE  TRUE

[1]  TRUE FALSE FALSE  TRUE  TRUE  TRUE

[1] FALSE FALSE FALSE FALSE FALSE FALSE

[1] FALSE

[1] TRUE

[1] FALSE  TRUE FALSE  TRUE FALSE FALSE

In [19]:
# && and ||
# The longer form evaluates left to right examining only the first element of each vector
x=1:6
x>2
x<5
(x > 2) && (x < 5)
(x[1] > 2) & (x[1] < 5)

[1] FALSE FALSE  TRUE  TRUE  TRUE  TRUE

[1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE

[1] FALSE

[1] FALSE

In [20]:
x = 1; y = 2
(x == 1) & (y == 2)
(x == 1) && (y == 2)

[1] TRUE

[1] TRUE

In [21]:
z = 1:6
(z > 2) & (z < 5)
z[(z>2) & (z<5)]

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

[1] 3 4

In [22]:
z
z>2
z<5
(z > 2) && (z < 5)
z[(z > 2) && (z < 5)]

[1] 1 2 3 4 5 6

[1] FALSE FALSE  TRUE  TRUE  TRUE  TRUE

[1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE

[1] FALSE

integer(0)

In [23]:
(z > 2) && (z < 5)
z[(z > 0) && (z < 5)]  # R recylces the TRUE variable

[1] FALSE

[1] 1 2 3 4 5 6

In [24]:
z
z[TRUE]
# z[FALSE] ##output nothing

[1] 1 2 3 4 5 6

[1] 1 2 3 4 5 6

In [25]:
# more examples of && and ||
a=c(0,1,1)
b=c(0,0,1)
a & b
a | b
a && b # The longer form evaluates left to right examining only the first element of each vector
a || b
a=c(0,1,1)
b=c(1,0,1)
a & b
a | b
a && b
a || b
a=c(1,1,1)
b=c(1,0,1)
a & b
a | b
a && b
a || b

[1] FALSE FALSE  TRUE

[1] FALSE  TRUE  TRUE

[1] FALSE

[1] FALSE

[1] FALSE FALSE  TRUE

[1] TRUE TRUE TRUE

[1] FALSE

[1] TRUE

[1]  TRUE FALSE  TRUE

[1] TRUE TRUE TRUE

[1] TRUE

[1] TRUE

In [26]:
x # a scalar is like a vector with lengh =1
x>3
x[x>3]

[1] 1

[1] FALSE

numeric(0)

In [27]:
x[c(FALSE, FALSE, FALSE, TRUE, TRUE, TRUE)]
x<2 | x>3
x[x<2 | x>3]
x[c(TRUE, FALSE, FALSE, TRUE, TRUE, TRUE)]

[1] NA NA NA

[1] TRUE

[1] 1

[1]  1 NA NA NA

In [28]:
x=c(1,2,3,NA,4)
x
is.na(x)
mean(x)
mean(x, na.rm=TRUE)
all(!is.na(x))
any(is.na(x))
x[is.na(x)]=0
x
mean(x)
(1/0)*8 # NA is different from inf

[1]  1  2  3 NA  4

[1] FALSE FALSE FALSE  TRUE FALSE

[1] NA

[1] 2.5

[1] FALSE

[1] TRUE

[1] 1 2 3 0 4

[1] 2

[1] Inf

In [29]:
library() #list all installed packages
library(MASS)
head(survey)
tail(survey)
# data(survey, package="MASS")

Sex    Wr.Hnd NW.Hnd W.Hnd Fold    Pulse Clap    Exer Smoke Height M.I     
1 Female 18.5   18.0   Right R on L   92   Left    Some Never 173.00 Metric  
2 Male   19.5   20.5   Left  R on L  104   Left    None Regul 177.80 Imperial
3 Male   18.0   13.3   Right L on R   87   Neither None Occas     NA NA      
4 Male   18.8   18.9   Right R on L   NA   Neither None Never 160.00 Metric  
5 Male   20.0   20.0   Right Neither  35   Right   Some Never 165.00 Metric  
6 Female 18.0   17.7   Right L on R   64   Right   Some Never 172.72 Imperial
  Age   
1 18.250
2 17.583
3 16.917
4 20.333
5 23.667
6 21.000

Sex    Wr.Hnd NW.Hnd W.Hnd Fold   Pulse Clap  Exer Smoke Height M.I     
232 Male   18.0   16.0   Right R on L NA    Right Some Never 180.34 Imperial
233 Female 18.0   18.0   Right L on R 85    Right Some Never 165.10 Imperial
234 Female 18.5   18.0   Right L on R 88    Right Some Never 160.00 Metric  
235 Female 17.5   16.5   Right R on L NA    Right Some Never 170.00 Metric  
236 Male   21.0   21.5   Right R on L 90    Right Some Never 183.00 Metric  
237 Female 17.6   17.3   Right R on L 85    Right Freq Never 168.50 Metric  
    Age   
232 20.750
233 17.667
234 16.917
235 18.583
236 17.167
237 17.750

In [30]:
islands

Africa       Antarctica             Asia        Australia 
           11506             5500            16988             2968 
    Axel Heiberg           Baffin            Banks           Borneo 
              16              184               23              280 
         Britain          Celebes            Celon             Cuba 
              84               73               25               43 
           Devon        Ellesmere           Europe        Greenland 
              21               82             3745              840 
          Hainan       Hispaniola         Hokkaido           Honshu 
              13               30               30               89 
         Iceland          Ireland             Java           Kyushu 
              40               33               49               14 
           Luzon       Madagascar         Melville         Mindanao 
              42              227               16               36 
        Moluccas      New Britain       New Guinea  New Zealand (N) 
              29               15              306               44 
 New Zealand (S)     Newfoundland    North America    Novaya Zemlya 
              58               43             9390               32 
 Prince of Wales         Sakhalin    South America      Southampton 
              13               29             6795               16 
     Spitsbergen          Sumatra           Taiwan         Tasmania 
              15              183               14               26 
Tierra del Fuego            Timor        Vancouver         Victoria 
              19               13               12               82

In [31]:
# islands
class(islands)
head(islands)
islands[1]
islands['Africa']

[1] "numeric"

Africa   Antarctica         Asia    Australia Axel Heiberg       Baffin 
       11506         5500        16988         2968           16          184

Africa 
 11506

Africa 
 11506

In [32]:
library(help=MASS)
library(MASS)
find.package() # list all loaded packages
detach("package:MASS", unload=TRUE)
find.package()

[1] "C:/anaconda3/Lib/R/library/MASS"     
[2] "C:/anaconda3/Lib/R/library/stats"    
[3] "C:/anaconda3/Lib/R/library/graphics" 
[4] "C:/anaconda3/Lib/R/library/grDevices"
[5] "C:/anaconda3/Lib/R/library/utils"    
[6] "C:/anaconda3/Lib/R/library/datasets" 
[7] "C:/anaconda3/Lib/R/library/methods"  
[8] "C:/anaconda3/lib/R/library/base"

[1] "C:/anaconda3/Lib/R/library/stats"    
[2] "C:/anaconda3/Lib/R/library/graphics" 
[3] "C:/anaconda3/Lib/R/library/grDevices"
[4] "C:/anaconda3/Lib/R/library/utils"    
[5] "C:/anaconda3/Lib/R/library/datasets" 
[6] "C:/anaconda3/Lib/R/library/methods"  
[7] "C:/anaconda3/lib/R/library/base"

In [33]:
whales=scan() #doesn't work in jupyter

In [34]:
data()

In [35]:
head(rock)

area peri    shape     perm
1 4990 2791.90 0.0903296  6.3
2 7002 3892.60 0.1486220  6.3
3 7558 3930.66 0.1833120  6.3
4 7352 3869.32 0.1170630  6.3
5 7943 3948.54 0.1224170 17.1
6 7979 4010.15 0.1670450 17.1

In [21]:
numbers=scan(file="numbers.txt");numbers


[1] 12345896

In [ ]:
mytable=read.table(file="table.txt", header=TRUE);mytable
# read.table(file=file.choose()) 
class(mytable)

In [ ]:
LETTERS
data.frame(index=1:26, symbol=LETTERS)

In [ ]:
?data.frame

In [ ]:
mydata=data.frame(col1=1:3, col2=4:6, col3=c('x', 'y', 'z'));mydata

In [ ]:
# col1=9
# rm(col1)
# ls()
names(mydata)
attach(mydata)
col1
col2
# detach(mydata)
# # col1
# # col1
# # col2
mydata$col1
with(mydata, col1)
with(mydata, mean(col1))

In [1]:
library(ISwR)
data(thuesen)
head(thuesen)
names(thuesen)
attach(thuesen) #add namespace
blood.glucose
detach(thuesen) #remove namespace
thuesen$blood.glucose

blood.glucose short.velocity
1 15.3          1.76          
2 10.8          1.34          
3  8.1          1.27          
4 19.5          1.47          
5  7.2          1.27          
6  5.3          1.49

[1] "blood.glucose"  "short.velocity"

[1] 15.3 10.8  8.1 19.5  7.2  5.3  9.3 11.1  7.5 12.2  6.7  5.2 19.0 15.1  6.7
[16]  8.6  4.2 10.3 12.5 16.1 13.3  4.9  8.8  9.5

[1] 15.3 10.8  8.1 19.5  7.2  5.3  9.3 11.1  7.5 12.2  6.7  5.2 19.0 15.1  6.7
[16]  8.6  4.2 10.3 12.5 16.1 13.3  4.9  8.8  9.5

In [2]:
with(thuesen, blood.glucose) # with context
with(thuesen, mean(blood.glucose))
with(thuesen, range(blood.glucose))

[1] 15.3 10.8  8.1 19.5  7.2  5.3  9.3 11.1  7.5 12.2  6.7  5.2 19.0 15.1  6.7
[16]  8.6  4.2 10.3 12.5 16.1 13.3  4.9  8.8  9.5

[1] 10.3

[1]  4.2 19.5

In [3]:
head(energy)
class(energy)
energy[energy$stature== "lean",]

expend stature
1  9.21  obese  
2  7.53  lean   
3  7.48  lean   
4  8.08  lean   
5  8.09  lean   
6 10.15  lean

[1] "data.frame"

expend stature
2   7.53  lean   
3   7.48  lean   
4   8.08  lean   
5   8.09  lean   
6  10.15  lean   
7   8.40  lean   
8  10.88  lean   
9   6.13  lean   
10  7.90  lean   
13  7.05  lean   
16  7.48  lean   
20  7.58  lean   
22  8.11  lean

In [4]:
energy$stature== "lean"

[1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE
[13]  TRUE FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE  TRUE

In [5]:
energy$expend
order(energy$expend)

[1]  9.21  7.53  7.48  8.08  8.09 10.15  8.40 10.88  6.13  7.90 11.51 12.79
[13]  7.05 11.85  9.97  7.48  8.79  9.69  9.68  7.58  9.19  8.11

[1]  9 13  3 16  2 20 10  4  5 22  7 17 21  1 19 18 15  6  8 11 14 12

In [6]:
energy$stature
order(energy$stature)
order(energy$stature, energy$expend)

[1] obese lean  lean  lean  lean  lean  lean  lean  lean  lean  obese obese
[13] lean  obese obese lean  obese obese obese lean  obese lean 
Levels: lean obese

[1]  2  3  4  5  6  7  8  9 10 13 16 20 22  1 11 12 14 15 17 18 19 21

[1]  9 13  3 16  2 20 10  4  5 22  7  6  8 17 21  1 19 18 15 11 14 12

In [7]:
energy[order(energy$expend),]
energy[order(energy$stature, energy$expend),]
energy[with(energy, order(stature, expend)),] # with context

expend stature
9   6.13  lean   
13  7.05  lean   
3   7.48  lean   
16  7.48  lean   
2   7.53  lean   
20  7.58  lean   
10  7.90  lean   
4   8.08  lean   
5   8.09  lean   
22  8.11  lean   
7   8.40  lean   
17  8.79  obese  
21  9.19  obese  
1   9.21  obese  
19  9.68  obese  
18  9.69  obese  
15  9.97  obese  
6  10.15  lean   
8  10.88  lean   
11 11.51  obese  
14 11.85  obese  
12 12.79  obese

expend stature
9   6.13  lean   
13  7.05  lean   
3   7.48  lean   
16  7.48  lean   
2   7.53  lean   
20  7.58  lean   
10  7.90  lean   
4   8.08  lean   
5   8.09  lean   
22  8.11  lean   
7   8.40  lean   
6  10.15  lean   
8  10.88  lean   
17  8.79  obese  
21  9.19  obese  
1   9.21  obese  
19  9.68  obese  
18  9.69  obese  
15  9.97  obese  
11 11.51  obese  
14 11.85  obese  
12 12.79  obese

expend stature
9   6.13  lean   
13  7.05  lean   
3   7.48  lean   
16  7.48  lean   
2   7.53  lean   
20  7.58  lean   
10  7.90  lean   
4   8.08  lean   
5   8.09  lean   
22  8.11  lean   
7   8.40  lean   
6  10.15  lean   
8  10.88  lean   
17  8.79  obese  
21  9.19  obese  
1   9.21  obese  
19  9.68  obese  
18  9.69  obese  
15  9.97  obese  
11 11.51  obese  
14 11.85  obese  
12 12.79  obese

In [8]:
subset(energy, stature=="lean" & expend>8)
energy[energy$stature== "lean" & energy$expend>8, ]

expend stature
4   8.08  lean   
5   8.09  lean   
6  10.15  lean   
7   8.40  lean   
8  10.88  lean   
22  8.11  lean

expend stature
4   8.08  lean   
5   8.09  lean   
6  10.15  lean   
7   8.40  lean   
8  10.88  lean   
22  8.11  lean

In [9]:
x=split(energy$expend, energy$stature) # split the data in energy$expend into the groups defined by energy$stature
class(x)
x

[1] "list"

$lean
 [1]  7.53  7.48  8.08  8.09 10.15  8.40 10.88  6.13  7.90  7.05  7.48  7.58
[13]  8.11

$obese
[1]  9.21 11.51 12.79 11.85  9.97  8.79  9.69  9.68  9.19

In [10]:
split(1:10, c("A", "B"))
#1 2 3 4 5 6 7 8 9 10
#A B A B A B A B A B 

# list
# A: 1,3,5,7,9
# B: 2,4,6,8,10

$A
[1] 1 3 5 7 9

$B
[1]  2  4  6  8 10

In [11]:
x$lean
x[[1]]

[1]  7.53  7.48  8.08  8.09 10.15  8.40 10.88  6.13  7.90  7.05  7.48  7.58
[13]  8.11

[1]  7.53  7.48  8.08  8.09 10.15  8.40 10.88  6.13  7.90  7.05  7.48  7.58
[13]  8.11

In [12]:
energy[[1]]

[1]  9.21  7.53  7.48  8.08  8.09 10.15  8.40 10.88  6.13  7.90 11.51 12.79
[13]  7.05 11.85  9.97  7.48  8.79  9.69  9.68  7.58  9.19  8.11

In [13]:
x=list(a=1:4, b=5:9, c=c('hello', 'world'), mymatrix=matrix(1:6, 2,3))
x
# x$m[2,2]
names(x)
x[['mymatrix']][,2]
# x$a
# x[[1]]
# x[[2]]
# x[['c']]

$a
[1] 1 2 3 4

$b
[1] 5 6 7 8 9

$c
[1] "hello" "world"

$mymatrix
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

[1] "a"        "b"        "c"        "mymatrix"

[1] 3 4

In [14]:
ls()
rm(a)
ls()

[1] "thuesen" "x"

Warning message in rm(a):
"object 'a' not found"

[1] "thuesen" "x"

In [15]:
getwd()

[1] "C:/Users/madhurima singh/Desktop/R test"

In [16]:
file.show("table.txt")

Warning message in file(con, "r"):
"cannot open file 'table.txt': No such file or directory"

ERROR: Error in file(con, "r"): cannot open the connection


In [ ]:
file.show("table.csv")

In [ ]:
read.table

In [ ]:
mytable=read.table(file="table.txt", header=TRUE, sep=" ");mytable
class(mytable)
sapply(mytable, class) #get data type for each column

In [ ]:
mytable
write.table(mytable, file="mytable.txt")

In [ ]:
?write.table

In [ ]:
file.show("mytable.txt")

In [ ]:
# write.csv(mytable, file="mytable.csv")
write.csv(mytable, file="mytable.csv", row.names=FALSE) #do not include row numbers

In [ ]:
file.show("mytable.csv")

In [ ]:
mytable=read.csv(file="mytable.csv", header=TRUE);mytable
names(mytable)

In [ ]:
mytable=read.csv(file="table.csv", header=TRUE);mytable
names(mytable)

In [ ]:
mytable=read.csv(file="table.txt", header=TRUE);mytable
names(mytable)

In [ ]:
lines=readLines("table.csv")
lines
lines=readLines("table.txt")
lines
lines[1]
lines[2]
lines[3]

In [ ]:
?writeLines

In [23]:
fileConn<-file("output.txt")
writeLines(c("Hello","World"), fileConn)
close(fileConn)

In [24]:
x=data.frame(a=1, b=2); x
dput(x)

a b
1 1 2

structure(list(a = 1, b = 2), class = "data.frame", row.names = c(NA, 
-1L))


In [25]:
str(x)

'data.frame':	1 obs. of  2 variables:
 $ a: num 1
 $ b: num 2


In [26]:
summary(x)

       a           b    
 Min.   :1   Min.   :2  
 1st Qu.:1   1st Qu.:2  
 Median :1   Median :2  
 Mean   :1   Mean   :2  
 3rd Qu.:1   3rd Qu.:2  
 Max.   :1   Max.   :2  

In [27]:
dput(x, file="x.R")

In [28]:
file.show("x.R")

In [29]:
dget("x.R")
structure(list(a = 1, b = 2), class = "data.frame", row.names = c(NA, 
-1L))
data.frame(a=1, b=2)

a b
1 1 2

a b
1 1 2

a b
1 1 2

In [30]:
y=dget("x.R") # you can think dget inserts the content here.
y

a b
1 1 2

In [31]:
y=structure(list(a = 1, b = 2), class = "data.frame", row.names = c(NA, 
-1L))
y

a b
1 1 2

In [32]:
print("====================")
x=8
y=9
# dump(c('x', 'y'))  # by default it dumps to file "dumpdata.R"
dump(c('x', 'y'), file='xy.R')

[1] "===================="


In [33]:
file.show("xy.R")

In [34]:
ls()
rm(x, y)
ls()

[1] "fileConn" "numbers"  "thuesen"  "x"        "y"

[1] "fileConn" "numbers"  "thuesen"

In [35]:
source("xy.R") # source both inserts and executes the content here
x

[1] 8

In [36]:
x <- serialize(list(1,2,3), NULL)
print(x)
y=unserialize(x)
y

 [1] 58 0a 00 00 00 02 00 03 05 01 00 02 03 00 00 00 00 13 00 00 00 03 00 00 00
[26] 0e 00 00 00 01 3f f0 00 00 00 00 00 00 00 00 00 0e 00 00 00 01 40 00 00 00
[51] 00 00 00 00 00 00 00 0e 00 00 00 01 40 08 00 00 00 00 00 00


[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

In [37]:
a=data.frame(x = rnorm(100), y = runif(100)); head(a)
b=c(3, 4.4, 1 / 3); b

x          y        
1 -1.3714542 0.2365891
2  0.6835109 0.9393540
3  1.3687210 0.5520382
4 -0.1340534 0.7969643
5  0.3069792 0.2503235
6  1.6355337 0.1056800

[1] 3.0000000 4.4000000 0.3333333

In [38]:
save(a, b, file = "mydata.rda")

In [39]:
rm(a, b)
ls()

[1] "fileConn" "numbers"  "thuesen"  "x"        "y"

In [40]:
load("mydata.rda")

In [41]:
ls()
head(a)
b

[1] "a"        "b"        "fileConn" "numbers"  "thuesen"  "x"        "y"

x          y        
1 -1.3714542 0.2365891
2  0.6835109 0.9393540
3  1.3687210 0.5520382
4 -0.1340534 0.7969643
5  0.3069792 0.2503235
6  1.6355337 0.1056800

[1] 3.0000000 4.4000000 0.3333333

In [42]:
save.image(file="alldata.RData") #then this file can be opened in another R session or even on different computer.

In [43]:
mult <- function(x, y) {
    x*y
}

In [44]:
mult(9, 9)

[1] 81

In [45]:
dput(mult, file="mymult.R")

In [46]:
file.show("mymult.R")

In [47]:
dump(c('mult'), file="myfun.R")

In [48]:
file.show("myfun.R")

In [49]:
# calling the functions
# this is the file where we will call the functions in myfun.R and mymult.R
times <- dget("mymult.R")
times(-4:4, 2)

source("myfun.R")
mult(-4:4, 2)

[1] -8 -6 -4 -2  0  2  4  6  8

[1] -8 -6 -4 -2  0  2  4  6  8

In [50]:
x=5

if (x>9) 
{
    print(2)
} else
{
    print(4)
}

[1] 4


In [51]:
x=8

if(x<5){
    print(1)
} else if (x<10)  #the conditions are better to be exclusive from each other
# } else if (5<=x & x<10) 
        {
        print(2)
        }else{ # x>=10
           print(3)
        }

[1] 2


In [52]:
x=runif(1, 0, 10);x
if (x>3) print(10) else print(0)


[1] 5.287798

[1] 10


In [53]:
?runif

In [54]:
x=runif(1, 0, 10)
if (x>3) 10 else 0

[1] 10

In [55]:
x=runif(1, 0, 10)
y=if (x>3) 10 else 0
print(y)
# x=runif(1, 0, 10)
print(ifelse(x>3, 10, 0))

[1] 0
[1] 0


In [56]:
ifelse #it creates both vectors, the yes and the no, and then subsets.

function (test, yes, no) 
{
    if (is.atomic(test)) {
        if (typeof(test) != "logical") 
            storage.mode(test) <- "logical"
        if (length(test) == 1 && is.null(attributes(test))) {
            if (is.na(test)) 
                return(NA)
            else if (test) {
                if (length(yes) == 1) {
                  yat <- attributes(yes)
                  if (is.null(yat) || (is.function(yes) && identical(names(yat), 
                    "srcref"))) 
                    return(yes)
                }
            }
            else if (length(no) == 1) {
                nat <- attributes(no)
                if (is.null(nat) || (is.function(no) && identical(names(nat), 
                  "srcref"))) 
                  return(no)
            }
        }
    }
    else test <- if (isS4(test)) 
        methods::as(test, "logical")
    else as.logical(test)
    ans <- test
    ok <- !is.na(test)
    if (any(test[ok])) 
        ans[test & ok] <- rep(yes, length.out = length(ans))[test & 
            ok]
    if (any(!test[ok])) 
        ans[!test & ok] <- rep(no, length.out = length(ans))[!test & 
            ok]
    ans
}
<bytecode: 0x00000000271a05c0>
<environment: namespace:base>

In [57]:
rep(c(1,2,3), length.out =5)
# ?rep

[1] 1 2 3 1 2

In [58]:
x=6:-4
sqrt(x)

Warning message in sqrt(x):
"NaNs produced"

[1] 2.449490 2.236068 2.000000 1.732051 1.414214 1.000000 0.000000      NaN
 [9]      NaN      NaN      NaN

In [59]:
y=ifelse(x>=0, x, 0);y
sqrt(y)

[1] 6 5 4 3 2 1 0 0 0 0 0

[1] 2.449490 2.236068 2.000000 1.732051 1.414214 1.000000 0.000000 0.000000
 [9] 0.000000 0.000000 0.000000

In [60]:
ifelse(x>=0, sqrt(x), 0)

Warning message in sqrt(x):
"NaNs produced"

[1] 2.449490 2.236068 2.000000 1.732051 1.414214 1.000000 0.000000 0.000000
 [9] 0.000000 0.000000 0.000000

In [61]:
ifelse(x>=0, {print(x);sqrt(x)}, {print("negative");0}) #recycling happens within ifelse function as seen above

 [1]  6  5  4  3  2  1  0 -1 -2 -3 -4


Warning message in sqrt(x):
"NaNs produced"

[1] "negative"


[1] 2.449490 2.236068 2.000000 1.732051 1.414214 1.000000 0.000000 0.000000
 [9] 0.000000 0.000000 0.000000

In [62]:
x=c(1,2,3)
typeof(x)  #R internal type or storage mode
class(x)   #object's class attribute, if not, it use the result of typeof
# ?typeof
# ?class
y=data.frame(x=1:2, y=3:4)
typeof(y)
class(y)

[1] "double"

[1] "numeric"

[1] "list"

[1] "data.frame"

In [63]:
yes <- 1:3
no <- pi^(0:3)
typeof(ifelse(NA,    yes, no)) # logical
typeof(ifelse(TRUE,  yes, no)) # integer
typeof(ifelse(FALSE, yes, no)) # double

[1] "logical"

[1] "integer"

[1] "double"

In [64]:
for(i in 1:10) print(i)

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [65]:
x=c('a', 'b', 'c')
for (i in x) print(i)
for (i in 1:length(x)) print(x[i])

[1] "a"
[1] "b"
[1] "c"
[1] "a"
[1] "b"
[1] "c"


In [66]:
x=c('a', 'b', 'c')
# x=c()
1:length(x)
for (i in 1:length(x)) print(i)
"=================="
seq_along(x) #generate the index vector safely
for (i in seq_along(x)) print(i)

[1] 1 2 3

[1] 1
[1] 2
[1] 3


[1] "=================="

[1] 1 2 3

[1] 1
[1] 2
[1] 3


In [67]:
?seq_along

In [68]:
for (i in seq_along(x)) print(i);print(i*2)
"===================="
for (i in seq_along(x)) {print(i);print(i*2)}

[1] 1
[1] 2
[1] 3
[1] 6


[1] "===================="

[1] 1
[1] 2
[1] 2
[1] 4
[1] 3
[1] 6


In [69]:
x=matrix(1:6, 2, 3)
print(x)

nrow(x)
ncol(x)
seq_len(nrow(x))
seq_len(ncol(x))
seq_len(10)
seq_len(0)
seq_along(10)
seq_along(1:10)

for(i in seq_len(nrow(x))) {
    for (j in seq_len(ncol(x))) {
        print(paste("i=", i, "j=", j, "x=", x[i, j], sep=" "))
#         print(x[i,j])
        }
}

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


[1] 2

[1] 3

[1] 1 2

[1] 1 2 3

[1]  1  2  3  4  5  6  7  8  9 10

integer(0)

[1] 1

[1]  1  2  3  4  5  6  7  8  9 10

[1] "i= 1 j= 1 x= 1"
[1] "i= 1 j= 2 x= 3"
[1] "i= 1 j= 3 x= 5"
[1] "i= 2 j= 1 x= 2"
[1] "i= 2 j= 2 x= 4"
[1] "i= 2 j= 3 x= 6"


In [70]:
x <- 1
repeat {
    print(x)
    x = x+1
    if (x == 6) break
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [73]:
pi = 1

f1 <- function(n){

{for (i in range(0:n))
        {x = (i * 2 + 3) 
        #val = num/x

       if(i%%2==0){
    
    pi =  pi - (1/x) 

}else
{
    pi = pi + 1/x
        }
    
  }
  pi = pi*4 
 
}
  return (pi)    
  
 }

In [75]:
f1(100)

[1] 2.646962

In [76]:
compute_pi <- function(m) {
    s = 0
    sign = 1
    for (n in 0:m) {
        s = s + sign / (2 * n + 1)
        sign = -sign
    }
    4 * s
}

In [77]:
compute_pi(100)

[1] 3.151493