In [103]:
library(stringr)

In [104]:
homicides = readLines("homicides.txt")
head(homicides)

[1] "39.311024, -76.674227, iconHomicideShooting, 'p2', '<dl><dt>Leon Nelson</dt><dd class=\"address\">3400 Clifton Ave.<br />Baltimore, MD 21216</dd><dd>black male, 17 years old</dd><dd>Found on January 1, 2007</dd><dd>Victim died at Shock Trauma</dd><dd>Cause: shooting</dd></dl>'"         
[2] "39.312641, -76.698948, iconHomicideShooting, 'p3', '<dl><dt>Eddie Golf</dt><dd class=\"address\">4900 Challedon Road<br />Baltimore, MD 21207</dd><dd>black male, 26 years old</dd><dd>Found on January 2, 2007</dd><dd>Victim died at scene</dd><dd>Cause: shooting</dd></dl>'"               
[3] "39.309781, -76.649882, iconHomicideBluntForce, 'p4', '<dl><dt>Nelsene Burnette</dt><dd class=\"address\">2000 West North Ave<br />Baltimore, MD 21217</dd><dd>black female, 44 years old</dd><dd>Found on January 2, 2007</dd><dd>Victim died at scene</dd><dd>Cause: blunt force</dd></dl>'"  
[4] "39.363925, -76.598772, iconHomicideAsphyxiation, 'p5', '<dl><dt>Thomas MacKenney</dt><dd class=\"address\">5900 Northwood Drive<br />Baltimore, MD 21212</dd><dd>black male, 21 years old</dd><dd>Found on January 3, 2007</dd><dd>Victim died at scene</dd><dd>Cause: asphyxiation</dd></dl>'"
[5] "39.238928, -76.602718, iconHomicideBluntForce, 'p6', '<dl><dt>Edward Canupp</dt><dd class=\"address\">500 Maude Ave.<br />Baltimore, MD 21225</dd><dd>white male, 61 years old</dd><dd>Found on January 5, 2007</dd><dd>Victim died at scene</dd><dd>Cause: blunt force</dd></dl>'"            
[6] "39.352676, -76.607979, iconHomicideShooting, 'p7', '<dl><dt>Michael Cunningham</dt><dd class=\"address\">5200 Ready Ave.<br />Baltimore, MD 21212</dd><dd>black male, 46 years old</dd><dd>Found on January 5, 2007</dd><dd>Victim died at JHH</dd><dd>Cause: shooting</dd></dl>'"

[1] "39.311024, -76.674227, iconHomicideShooting, 'p2', '<dl><dt>Leon Nelson</dt><dd class=\"address\">3400 Clifton Ave.<br />Baltimore, MD 21216</dd><dd>black male, 17 years old</dd><dd>Found on January 1, 2007</dd><dd>Victim died at Shock Trauma</dd><dd>Cause: shooting</dd></dl>'"         
[2] "39.312641, -76.698948, iconHomicideShooting, 'p3', '<dl><dt>Eddie Golf</dt><dd class=\"address\">4900 Challedon Road<br />Baltimore, MD 21207</dd><dd>black male, 26 years old</dd><dd>Found on January 2, 2007</dd><dd>Victim died at scene</dd><dd>Cause: shooting</dd></dl>'"               
[3] "39.309781, -76.649882, iconHomicideBluntForce, 'p4', '<dl><dt>Nelsene Burnette</dt><dd class=\"address\">2000 West North Ave<br />Baltimore, MD 21217</dd><dd>black female, 44 years old</dd><dd>Found on January 2, 2007</dd><dd>Victim died at scene</dd><dd>Cause: blunt force</dd></dl>'"  
[4] "39.363925, -76.598772, iconHomicideAsphyxiation, 'p5', '<dl><dt>Thomas MacKenney</dt><dd class=\"address\">5900 Northwood Drive<br />Baltimore, MD 21212</dd><dd>black male, 21 years old</dd><dd>Found on January 3, 2007</dd><dd>Victim died at scene</dd><dd>Cause: asphyxiation</dd></dl>'"
[5] "39.238928, -76.602718, iconHomicideBluntForce, 'p6', '<dl><dt>Edward Canupp</dt><dd class=\"address\">500 Maude Ave.<br />Baltimore, MD 21225</dd><dd>white male, 61 years old</dd><dd>Found on January 5, 2007</dd><dd>Victim died at scene</dd><dd>Cause: blunt force</dd></dl>'"            
[6] "39.352676, -76.607979, iconHomicideShooting, 'p7', '<dl><dt>Michael Cunningham</dt><dd class=\"address\">5200 Ready Ave.<br />Baltimore, MD 21212</dd><dd>black male, 46 years old</dd><dd>Found on January 5, 2007</dd><dd>Victim died at JHH</dd><dd>Cause: shooting</dd></dl>'"

In [105]:
grep("iconHomicideShooting", homicides)
homicides[2]

[1]   1   2   6   7   8   9  10  11  12  13  14  15  16  18  19  20  21  22
 [19]  23  24  25  26  28  29  30  31  32  33  34  35  36  37  38  39  40  41
 [37]  42  44  45  46  47  48  49  50  51  52  53  54  55  56  57  60  61  62
 [55]  63  64  67  68  69  70  71  72  74  75  77  78  79  80  81  82  84  85
 [73]  86  87  88  89  90  91  93  94  95  96  97  98  99 100 101 102 103 104
 [91] 105 106 107 108 109 112 113 114 115 117 119 120 121 123 124 125 126 127
[109] 129 130 132 133 134 135 136 138 139 140 141 142 143 144 146 147 148 149
[127] 151 152 154 155 156 157 158 159 160 161 163 169 170 171 172 173 174 175
[145] 176 177 178 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194
[163] 195 196 197 200 201 202 203 204 205 206 207 208 209 210 211 214 215 216
[181] 217 219 220 221 222 223 225 229 231 232 233 234 235 237 239 241 242 243
[199] 244 245 247 248 249 250 251 252 253 254 255 256 257 258 260 261 262 263
[217] 265 266 269 271 272 273 275 276 277 278 279 280

[1]   1   2   6   7   8   9  10  11  12  13  14  15  16  18  19  20  21  22
 [19]  23  24  25  26  28  29  30  31  32  33  34  35  36  37  38  39  40  41
 [37]  42  44  45  46  47  48  49  50  51  52  53  54  55  56  57  60  61  62
 [55]  63  64  67  68  69  70  71  72  74  75  77  78  79  80  81  82  84  85
 [73]  86  87  88  89  90  91  93  94  95  96  97  98  99 100 101 102 103 104
 [91] 105 106 107 108 109 112 113 114 115 117 119 120 121 123 124 125 126 127
[109] 129 130 132 133 134 135 136 138 139 140 141 142 143 144 146 147 148 149
[127] 151 152 154 155 156 157 158 159 160 161 163 169 170 171 172 173 174 175
[145] 176 177 178 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194
[163] 195 196 197 200 201 202 203 204 205 206 207 208 209 210 211 214 215 216
[181] 217 219 220 221 222 223 225 229 231 232 233 234 235 237 239 241 242 243
[199] 244 245 247 248 249 250 251 252 253 254 255 256 257 258 260 261 262 263
[217] 265 266 269 271 272 273 275 276 277 278 279 280

[1] "39.312641, -76.698948, iconHomicideShooting, 'p3', '<dl><dt>Eddie Golf</dt><dd class=\"address\">4900 Challedon Road<br />Baltimore, MD 21207</dd><dd>black male, 26 years old</dd><dd>Found on January 2, 2007</dd><dd>Victim died at scene</dd><dd>Cause: shooting</dd></dl>'"

[1] "39.312641, -76.698948, iconHomicideShooting, 'p3', '<dl><dt>Eddie Golf</dt><dd class=\"address\">4900 Challedon Road<br />Baltimore, MD 21207</dd><dd>black male, 26 years old</dd><dd>Found on January 2, 2007</dd><dd>Victim died at scene</dd><dd>Cause: shooting</dd></dl>'"

In [106]:
length(grep("iconHomicideShooting", homicides))

[1] 228

[1] 228

In [107]:
length(grep("iconHomicideShooting|icon_homicide_shooting", homicides))

[1] 1003

[1] 1003

In [108]:
length(grep("Cause: shooting", homicides))

[1] 228

[1] 228

In [109]:
length(grep("Cause: [Ss]hooting", homicides))

[1] 1003

[1] 1003

In [110]:
length(grep("[Ss]hooting", homicides))

[1] 1005

[1] 1005

In [111]:
i <- grep("[cC]ause: [Ss]hooting", homicides)
j <- grep("[Ss]hooting", homicides)
str(i)
str(j)
setdiff(i, j)
'-------------------'
setdiff(j, i)

 int [1:1003] 1 2 6 7 8 9 10 11 12 13 ...
 int [1:1003] 1 2 6 7 8 9 10 11 12 13 ...
 int [1:1005] 1 2 6 7 8 9 10 11 12 13 ...
 int [1:1005] 1 2 6 7 8 9 10 11 12 13 ...


integer(0)

integer(0)

[1] "-------------------"

[1] 318 859

[1] "-------------------"

[1] 318 859

In [112]:
homicides[317]
homicides[318]

[1] "39.30124320000, -76.60280220000, icon_homicide_shooting, 'p469', '<dl><dt><a href=\"http://essentials.baltimoresun.com/micro_sun/homicides/victim/469/donte-graham\">Donte Graham</a></dt><dd class=\"address\">1100 Abbott Court<br />Baltimore, MD 21202</dd><dd>Race: Unknown<br />Gender: male<br />Age: 21 years old</dd><dd>Found on November 18, 2008</dd><dd>Victim died at Johns Hopkins Hospital</dd><dd>Cause: Shooting</dd><dd><a href=\"http://www.baltimoresun.com/news/local/baltimore_city/bal-shootings1118,0,2126326.story\">Read the article</a></dd></dl>'"

[1] "39.28322500000, -76.63946800000, icon_homicide_bluntforce, 'p472', '<dl><dt><a href=\"http://essentials.baltimoresun.com/micro_sun/homicides/victim/472/lyle-dimeler\">Lyle Dimeler</a></dt><dd class=\"address\">400 S. Calhoun St.<br />Baltimore, MD 21223</dd><dd>Race: Unknown<br />Gender: male<br />Age: 53 years old</dd><dd>Found on November 18, 2008</dd><dd>Victim died at Maryland Shock Trauma Center</dd><dd>Cause: Blunt Force</dd><dd><a href=\"http://www.baltimoresun.com/news/local/bal-shootingdeath1118,0,3571249.story\">Read the article</a></dd></dl>'"

[1] "39.30124320000, -76.60280220000, icon_homicide_shooting, 'p469', '<dl><dt><a href=\"http://essentials.baltimoresun.com/micro_sun/homicides/victim/469/donte-graham\">Donte Graham</a></dt><dd class=\"address\">1100 Abbott Court<br />Baltimore, MD 21202</dd><dd>Race: Unknown<br />Gender: male<br />Age: 21 years old</dd><dd>Found on November 18, 2008</dd><dd>Victim died at Johns Hopkins Hospital</dd><dd>Cause: Shooting</dd><dd><a href=\"http://www.baltimoresun.com/news/local/baltimore_city/bal-shootings1118,0,2126326.story\">Read the article</a></dd></dl>'"

[1] "39.28322500000, -76.63946800000, icon_homicide_bluntforce, 'p472', '<dl><dt><a href=\"http://essentials.baltimoresun.com/micro_sun/homicides/victim/472/lyle-dimeler\">Lyle Dimeler</a></dt><dd class=\"address\">400 S. Calhoun St.<br />Baltimore, MD 21223</dd><dd>Race: Unknown<br />Gender: male<br />Age: 53 years old</dd><dd>Found on November 18, 2008</dd><dd>Victim died at Maryland Shock Trauma Center</dd><dd>Cause: Blunt Force</dd><dd><a href=\"http://www.baltimoresun.com/news/local/bal-shootingdeath1118,0,3571249.story\">Read the article</a></dd></dl>'"

In [113]:
grep("^New", state.name)
grep("^New", state.name, value = TRUE)
grepl("^New", state.name)

[1] 29 30 31 32

[1] "New Hampshire" "New Jersey"    "New Mexico"    "New York"

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[25] FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE
[37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[49] FALSE FALSE

[1] 29 30 31 32

[1] "New Hampshire" "New Jersey"    "New Mexico"    "New York"

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[25] FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE
[37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[49] FALSE FALSE

In [114]:
x=regexpr("<dd>[F|f]ound(.*)</dd>", homicides[1:10])
x=regexpr("<dd>[F|f]ound(.*?)</dd>", homicides[1:10])
print(x)
print(homicides[1])
substr(homicides[1], 177, 177+93-1)
substr(homicides[1], 177, 177+33-1)
substr(homicides[1], 190, 190+15-1)

 [1] 177 178 188 189 178 182 178 187 182 183
attr(,"match.length")
 [1] 33 33 33 33 33 33 33 33 33 33
attr(,"index.type")
[1] "chars"
attr(,"useBytes")
[1] TRUE
[1] "39.311024, -76.674227, iconHomicideShooting, 'p2', '<dl><dt>Leon Nelson</dt><dd class=\"address\">3400 Clifton Ave.<br />Baltimore, MD 21216</dd><dd>black male, 17 years old</dd><dd>Found on January 1, 2007</dd><dd>Victim died at Shock Trauma</dd><dd>Cause: shooting</dd></dl>'"


[1] "<dd>Found on January 1, 2007</dd><dd>Victim died at Shock Trauma</dd><dd>Cause: shooting</dd>"

 [1] 177 178 188 189 178 182 178 187 182 183
attr(,"match.length")
 [1] 33 33 33 33 33 33 33 33 33 33
attr(,"index.type")
[1] "chars"
attr(,"useBytes")
[1] TRUE
[1] "39.311024, -76.674227, iconHomicideShooting, 'p2', '<dl><dt>Leon Nelson</dt><dd class=\"address\">3400 Clifton Ave.<br />Baltimore, MD 21216</dd><dd>black male, 17 years old</dd><dd>Found on January 1, 2007</dd><dd>Victim died at Shock Trauma</dd><dd>Cause: shooting</dd></dl>'"


[1] "<dd>Found on January 1, 2007</dd><dd>Victim died at Shock Trauma</dd><dd>Cause: shooting</dd>"

[1] "<dd>Found on January 1, 2007</dd>"

[1] "<dd>Found on January 1, 2007</dd>"

[1] "January 1, 2007"

[1] "January 1, 2007"

In [115]:
regmatches(homicides[1:10], x)

[1] "<dd>Found on January 1, 2007</dd>" "<dd>Found on January 2, 2007</dd>"
 [3] "<dd>Found on January 2, 2007</dd>" "<dd>Found on January 3, 2007</dd>"
 [5] "<dd>Found on January 5, 2007</dd>" "<dd>Found on January 5, 2007</dd>"
 [7] "<dd>Found on January 5, 2007</dd>" "<dd>Found on January 7, 2007</dd>"
 [9] "<dd>Found on January 8, 2007</dd>" "<dd>Found on January 8, 2007</dd>"

[1] "<dd>Found on January 1, 2007</dd>" "<dd>Found on January 2, 2007</dd>"
 [3] "<dd>Found on January 2, 2007</dd>" "<dd>Found on January 3, 2007</dd>"
 [5] "<dd>Found on January 5, 2007</dd>" "<dd>Found on January 5, 2007</dd>"
 [7] "<dd>Found on January 5, 2007</dd>" "<dd>Found on January 7, 2007</dd>"
 [9] "<dd>Found on January 8, 2007</dd>" "<dd>Found on January 8, 2007</dd>"

In [116]:
# ?sub
?regexec

In [117]:
str_c("a", "b") #no default sep
paste("a", "b") #default sep is space
str_c(letters[1:6],c("1","2"), sep=",")
str_c(letters[1:6],c("1","2"), sep=",", collapse = "___")

[1] "ab"

[1] "a b"

[1] "a,1" "b,2" "c,1" "d,2" "e,1" "f,2"

[1] "a,1___b,2___c,1___d,2___e,1___f,2"

[1] "ab"

[1] "a b"

[1] "a,1" "b,2" "c,1" "d,2" "e,1" "f,2"

[1] "a,1___b,2___c,1___d,2___e,1___f,2"

In [118]:
str_c(letters, letters)

[1] "aa" "bb" "cc" "dd" "ee" "ff" "gg" "hh" "ii" "jj" "kk" "ll" "mm" "nn" "oo"
[16] "pp" "qq" "rr" "ss" "tt" "uu" "vv" "ww" "xx" "yy" "zz"

[1] "aa" "bb" "cc" "dd" "ee" "ff" "gg" "hh" "ii" "jj" "kk" "ll" "mm" "nn" "oo"
[16] "pp" "qq" "rr" "ss" "tt" "uu" "vv" "ww" "xx" "yy" "zz"

In [119]:
str_length("abc")
str_length(NA)
nchar("abc")
nchar(NA)
nchar(NA, keepNA=FALSE)

[1] 3

[1] NA

[1] 3

[1] NA

[1] 2

[1] 3

[1] NA

[1] 3

[1] NA

[1] 2

In [120]:
x=factor(c(1,222,2,2,2,1,1))
x
str_length(x)

[1] 1   222 2   2   2   1   1  
Levels: 1 2 222

[1] 1   222 2   2   2   1   1  
Levels: 1 2 222

[1] 1 3 1 1 1 1 1

[1] 1 3 1 1 1 1 1

In [121]:
str_length(letters)

[1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

[1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

In [122]:
str_length(factor("abc"))

[1] 3

[1] 3

In [123]:
str_length("abc")
length("abc")
length(letters)

[1] 3

[1] 1

[1] 26

[1] 3

[1] 1

[1] 26

In [124]:
str<-c("abcdedf","aaa","bbb")
str
str_length(str)
str_length("ab")
str_length(NA)
x=str_length("");x
length("aass")
length(c('a', 'b'))
nchar("aa")
x=c(1,1,1,26,2)
factor(x)
str_length(factor(x))

[1] "abcdedf" "aaa"     "bbb"

[1] 7 3 3

[1] 2

[1] NA

[1] 0

[1] "abcdedf" "aaa"     "bbb"

[1] 7 3 3

[1] 2

[1] NA

[1] 0

[1] 1

[1] 1

[1] 2

[1] 2

[1] 2

[1] 1  1  1  26 2 
Levels: 1 2 26

[1] 2

[1] 1  1  1  26 2 
Levels: 1 2 26

[1] 1 1 1 2 1

[1] 1 1 1 2 1

In [125]:
letters
str_length(letters)
str_length(NA)
factor("abc")
str_length(factor("abc"))
str_length(c("i", "like", "programming", NA))

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

[1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

[1] NA

[1] abc
Levels: abc

[1] 3

[1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

[1] NA

[1] abc
Levels: abc

[1] 3

[1]  1  4 11 NA

[1]  1  4 11 NA

In [126]:
hw <- "123456789"

#str_sub(string,start=1L,end=-1L)  #get sub string, default start/end
str_sub(hw, 1, 6)
str_sub(hw, end = 4)
str_sub(hw, 8, 14)
str_sub(hw, 8)
str_sub(hw, c(1, 8), c(6, 14))

# Negative indices
str_sub(hw, -1)
str_sub(hw, -7)
str_sub(hw, end = -7)

[1] "123456"

[1] "1234"

[1] "89"

[1] "89"

[1] "123456" "89"

[1] "123456"

[1] "1234"

[1] "89"

[1] "89"

[1] "123456" "89"

[1] "9"

[1] "3456789"

[1] "123"

[1] "9"

[1] "3456789"

[1] "123"

In [127]:
#str_sub(string,start=1L,end=-1L)<-replacement
hw="123456789"
str_sub(hw,1,3)<-"hello"
hw
str_sub(hw,8,-2)<-"hello"
hw

[1] "hello456789"

[1] "hello456789"

[1] "hello45hello9"

[1] "hello45hello9"

In [128]:
str="123"
str_dup(str,3)
str_dup(str,1:3) 
c(str_dup(str, 1), str_dup(str, 2), str_dup(str, 3))

[1] "123123123"

[1] "123"       "123123"    "123123123"

[1] "123"       "123123"    "123123123"

[1] "123123123"

[1] "123"       "123123"    "123123123"

[1] "123"       "123123"    "123123123"

In [129]:
library(stringr)
fruit <- c("apple", "pear", "banana")
str_dup(fruit, 2)
str_dup(fruit, 1:3)
str_c("ba", str_dup("na", 0:5))

[1] "appleapple"   "pearpear"     "bananabanana"

[1] "apple"              "pearpear"           "bananabananabanana"

[1] "appleapple"   "pearpear"     "bananabanana"

[1] "apple"              "pearpear"           "bananabananabanana"

[1] "ba"           "bana"         "banana"       "bananana"     "banananana"  
[6] "bananananana"

[1] "ba"           "bana"         "banana"       "bananana"     "banananana"  
[6] "bananananana"

In [130]:
#str_trim(string,side="both")
a<-"  sadjlsa   "
str_trim(a,"left")
str_trim(a,"both")

[1] "sadjlsa   "

[1] "sadjlsa"

[1] "sadjlsa   "

[1] "sadjlsa"

In [131]:
str_pad("yellow",10,"left",pad="#")
str_pad("yellow",10,"right",pad="*")
str_pad(1:20,3,"left",pad="*")

[1] "####yellow"

[1] "yellow****"

[1] "**1" "**2" "**3" "**4" "**5" "**6" "**7" "**8" "**9" "*10" "*11" "*12"
[13] "*13" "*14" "*15" "*16" "*17" "*18" "*19" "*20"

[1] "####yellow"

[1] "yellow****"

[1] "**1" "**2" "**3" "**4" "**5" "**6" "**7" "**8" "**9" "*10" "*11" "*12"
[13] "*13" "*14" "*15" "*16" "*17" "*18" "*19" "*20"

In [132]:
str<-c("abcdedf","aaa","bbb")
str_count(str,"[^ab]")
str_detect(str,"[^ab]")

[1] 5 0 0

[1]  TRUE FALSE FALSE

[1] 5 0 0

[1]  TRUE FALSE FALSE

In [133]:
strs<-c("abcdedf","aaa","bbb")
mat="[^ab]"
str_match_all(string = strs, pattern = mat)

[[1]]
     [,1]
[1,] "c" 
[2,] "d" 
[3,] "e" 
[4,] "d" 
[5,] "f" 

[[2]]
     [,1]

[[3]]
     [,1]

[[1]]
     [,1]
[1,] "c" 
[2,] "d" 
[3,] "e" 
[4,] "d" 
[5,] "f" 

[[2]]
     [,1]

[[3]]
     [,1]

In [134]:
str<-c("abcdedf","aaa","bbb")
str_detect(str,"a")

[1]  TRUE  TRUE FALSE

[1]  TRUE  TRUE FALSE

In [135]:
str1<-c("sfdfg","ulkdsf","yfellofw")
x=str_locate(str1,"f.*") #matrix return the index of first position of the match and the end position (not the last match)
x

start end
[1,] 2     5  
[2,] 6     6  
[3,] 2     8

start end
[1,] 2     5  
[2,] 6     6  
[3,] 2     8

In [136]:
x=str_locate(str1,"f.*?")
# class(x)
x

start end
[1,] 2     2  
[2,] 6     6  
[3,] 2     2

start end
[1,] 2     2  
[2,] 6     6  
[3,] 2     2

In [137]:
str_locate(str1,"f.*?f")

start end
[1,]  2     4 
[2,] NA    NA 
[3,]  2     7

start end
[1,]  2     4 
[2,] NA    NA 
[3,]  2     7

In [138]:
x=str_locate_all(str1,"f.") #list of matrix, all indices of matches
class(x)
class(x[[1]])
x

[1] "list"

[1] "matrix"

[1] "list"

[1] "matrix"

[[1]]
     start end
[1,]     2   3
[2,]     4   5

[[2]]
     start end

[[3]]
     start end
[1,]     2   3
[2,]     7   8

[[1]]
     start end
[1,]     2   3
[2,]     4   5

[[2]]
     start end

[[3]]
     start end
[1,]     2   3
[2,]     7   8

In [139]:
str<-c("abcde.df","aaa","ab(bb)ac")
str_extract(str,"a") #char vector
str_extract(str,"a.") #char vector
str_extract(str,"\\(.*\\)") #char vector
str_extract(str,"\\.") #char vector
str_extract_all(str,"a") #list of char vectors
str_extract_all(str,"a.") #list of char vectors

[1] "a" "a" "a"

[1] "a" "a" "a"

[1] "ab" "aa" "ab"

[1] "ab" "aa" "ab"

[1] NA     NA     "(bb)"

[1] NA     NA     "(bb)"

[1] "." NA  NA

[1] "." NA  NA

[[1]]
[1] "a"

[[2]]
[1] "a" "a" "a"

[[3]]
[1] "a" "a"

[[1]]
[1] "ab"

[[2]]
[1] "aa"

[[3]]
[1] "ab" "ac"

[[1]]
[1] "a"

[[2]]
[1] "a" "a" "a"

[[3]]
[1] "a" "a"

[[1]]
[1] "ab"

[[2]]
[1] "aa"

[[3]]
[1] "ab" "ac"

In [140]:
str3<-"addsjhadsk"
str_replace(str3,"a.*a","") #replace first match
str_replace_all(str3,"a","#") #replace all matches

[1] "dsk"

[1] "#ddsjh#dsk"

[1] "dsk"

[1] "#ddsjh#dsk"

In [141]:
#str_split(string,pattern,n=Inf)
str3<-"abcddseasdafs"
str_split(str3,"a",2)
x=str_split(str3,"a",3) #list of vectors
class(x);
print(x)

[[1]]
[1] ""             "bcddseasdafs"

[[1]]
[1] ""             "bcddseasdafs"

[1] "list"

[1] "list"

[[1]]
[1] ""       "bcddse" "sdafs" 

[[1]]
[1] ""       "bcddse" "sdafs" 



In [142]:
#str_split_fixed(string,pattern,n) # n is max
str3="cakdfjadsjafdasfsadfaf"
x=str_split_fixed(str3,"a",4) #matrix
class(x)
print(x)

[1] "matrix"

     [,1] [,2]   [,3]  [,4]         
[1,] "c"  "kdfj" "dsj" "fdasfsadfaf"


[1] "matrix"

     [,1] [,2]   [,3]  [,4]         
[1,] "c"  "kdfj" "dsj" "fdasfsadfaf"


In [143]:
#word(string,start=1L,end=start,sep=fixed("")) #substring without truncate word
data<-c("a bbbb cccc                 efg sadf    sdf")
word(data,2,-1)#-1 is the last
word(data,2, 19)
word(data,2, 20)
word(data,3, 20)

[1] "bbbb cccc                 efg sadf    sdf"

[1] "bbbb cccc                "

[1] "bbbb cccc                 efg"

[1] "bbbb cccc                 efg sadf    sdf"

[1] "bbbb cccc                "

[1] "bbbb cccc                 efg"

[1] "cccc                 efg"

[1] "cccc                 efg"

In [144]:
age<-c("21anos","22anos","23anos","24anos");age
age_replace<-str_replace(age,"anos","years old")
age_replace
age_replace<-str_replace(age,"anos","")
age_replace
age_numeric<-as.numeric(age_replace)
age_numeric

[1] "21anos" "22anos" "23anos" "24anos"

[1] "21years old" "22years old" "23years old" "24years old"

[1] "21anos" "22anos" "23anos" "24anos"

[1] "21years old" "22years old" "23years old" "24years old"

[1] "21" "22" "23" "24"

[1] "21" "22" "23" "24"

[1] 21 22 23 24

[1] 21 22 23 24

In [145]:
vec=c("a-b","b-c","d#e","u-p")
sep_loc=str_locate(vec,"-|#")
sep_loc
sep_loc[,1]-1
left=str_sub(vec,0,sep_loc[,1]-1)
left
right=str_sub(vec,sep_loc[,1]+1,str_length(vec))
right

start end
[1,] 2     2  
[2,] 2     2  
[3,] 2     2  
[4,] 2     2

[1] 1 1 1 1

start end
[1,] 2     2  
[2,] 2     2  
[3,] 2     2  
[4,] 2     2

[1] 1 1 1 1

[1] "a" "b" "d" "u"

[1] "a" "b" "d" "u"

[1] "b" "c" "e" "p"

[1] "b" "c" "e" "p"

In [146]:
strings <- c(" 219 733 8965", "329-293-8753 ", "banana", "595 794 7569", "387 287 6718", 
    "apple", "233.398.9187 ", "482 952 3315", "239 923 8115 and 842 566 4692", 
    "Work: 579-499-7527", "$1000", "Home: 543.355.3679")

phone <- "([2-9][0-9]{2})[- .]([0-9]{3})[- .]([0-9]{4})"

str_extract(string = strings, pattern = phone)  #return the first match
str_extract_all(string = strings, pattern = phone) # Extract/match all

[1] "219 733 8965" "329-293-8753" NA             "595 794 7569" "387 287 6718"
 [6] NA             "233.398.9187" "482 952 3315" "239 923 8115" "579-499-7527"
[11] NA             "543.355.3679"

[1] "219 733 8965" "329-293-8753" NA             "595 794 7569" "387 287 6718"
 [6] NA             "233.398.9187" "482 952 3315" "239 923 8115" "579-499-7527"
[11] NA             "543.355.3679"

[[1]]
[1] "219 733 8965"

[[2]]
[1] "329-293-8753"

[[3]]
character(0)

[[4]]
[1] "595 794 7569"

[[5]]
[1] "387 287 6718"

[[6]]
character(0)

[[7]]
[1] "233.398.9187"

[[8]]
[1] "482 952 3315"

[[9]]
[1] "239 923 8115" "842 566 4692"

[[10]]
[1] "579-499-7527"

[[11]]
character(0)

[[12]]
[1] "543.355.3679"

[[1]]
[1] "219 733 8965"

[[2]]
[1] "329-293-8753"

[[3]]
character(0)

[[4]]
[1] "595 794 7569"

[[5]]
[1] "387 287 6718"

[[6]]
character(0)

[[7]]
[1] "233.398.9187"

[[8]]
[1] "482 952 3315"

[[9]]
[1] "239 923 8115" "842 566 4692"

[[10]]
[1] "579-499-7527"

[[11]]
character(0)

[[12]]
[1] "543.355.3679"

In [147]:
str_match(string = strings, pattern = phone)  #return the longest match and its sub strings
str_match_all(string = strings, pattern = phone)

[,1]         [,2] [,3] [,4]
 [1,] 219 733 8965 219  733  8965
 [2,] 329-293-8753 329  293  8753
 [3,] NA           NA   NA   NA  
 [4,] 595 794 7569 595  794  7569
 [5,] 387 287 6718 387  287  6718
 [6,] NA           NA   NA   NA  
 [7,] 233.398.9187 233  398  9187
 [8,] 482 952 3315 482  952  3315
 [9,] 239 923 8115 239  923  8115
[10,] 579-499-7527 579  499  7527
[11,] NA           NA   NA   NA  
[12,] 543.355.3679 543  355  3679

[,1]         [,2] [,3] [,4]
 [1,] 219 733 8965 219  733  8965
 [2,] 329-293-8753 329  293  8753
 [3,] NA           NA   NA   NA  
 [4,] 595 794 7569 595  794  7569
 [5,] 387 287 6718 387  287  6718
 [6,] NA           NA   NA   NA  
 [7,] 233.398.9187 233  398  9187
 [8,] 482 952 3315 482  952  3315
 [9,] 239 923 8115 239  923  8115
[10,] 579-499-7527 579  499  7527
[11,] NA           NA   NA   NA  
[12,] 543.355.3679 543  355  3679

[[1]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "219 733 8965" "219" "733" "8965"

[[2]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "329-293-8753" "329" "293" "8753"

[[3]]
     [,1] [,2] [,3] [,4]

[[4]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "595 794 7569" "595" "794" "7569"

[[5]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "387 287 6718" "387" "287" "6718"

[[6]]
     [,1] [,2] [,3] [,4]

[[7]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "233.398.9187" "233" "398" "9187"

[[8]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "482 952 3315" "482" "952" "3315"

[[9]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "239 923 8115" "239" "923" "8115"
[2,] "842 566 4692" "842" "566" "4692"

[[10]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "579-499-7527" "579" "499" "7527"

[[11]]
     [,1] [,2] [,3] [,4]

[[12]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "543.355.3679" "543" "355" "3679"

[[1]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "219 733 8965" "219" "733" "8965"

[[2]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "329-293-8753" "329" "293" "8753"

[[3]]
     [,1] [,2] [,3] [,4]

[[4]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "595 794 7569" "595" "794" "7569"

[[5]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "387 287 6718" "387" "287" "6718"

[[6]]
     [,1] [,2] [,3] [,4]

[[7]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "233.398.9187" "233" "398" "9187"

[[8]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "482 952 3315" "482" "952" "3315"

[[9]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "239 923 8115" "239" "923" "8115"
[2,] "842 566 4692" "842" "566" "4692"

[[10]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "579-499-7527" "579" "499" "7527"

[[11]]
     [,1] [,2] [,3] [,4]

[[12]]
     [,1]           [,2]  [,3]  [,4]  
[1,] "543.355.3679" "543" "355" "3679"

In [148]:
mat="[^?.]$"
# mat=".$"
# mat="\.$"
# mat="\\.$"
strs=c('i like basketballs',
       '6 and 9',
       'dont worry... (we all) die anyway!',
       'who are you?',
       'here you go.',
       'Not in Baghdad',
       'helicopter under water? hmmm')
str_match_all(string = strs, pattern = mat)

[[1]]
     [,1]
[1,] "s" 

[[2]]
     [,1]
[1,] "9" 

[[3]]
     [,1]
[1,] "!" 

[[4]]
     [,1]

[[5]]
     [,1]

[[6]]
     [,1]
[1,] "d" 

[[7]]
     [,1]
[1,] "m"

[[1]]
     [,1]
[1,] "s" 

[[2]]
     [,1]
[1,] "9" 

[[3]]
     [,1]
[1,] "!" 

[[4]]
     [,1]

[[5]]
     [,1]

[[6]]
     [,1]
[1,] "d" 

[[7]]
     [,1]
[1,] "m"

In [149]:
#mat="(.*)"
mat="\\(.*\\)"
mat
strs=c('i like basketballs',
       '6 and 9',
       'dont worry... (we all) die anyway!',
       'who are you?',
       'here you go.',
       'Not in Baghdad',
       'helicopter under water? hmmm')
str_match_all(string = strs, pattern = mat)

[1] "\\(.*\\)"

[1] "\\(.*\\)"

[[1]]
     [,1]

[[2]]
     [,1]

[[3]]
     [,1]      
[1,] "(we all)"

[[4]]
     [,1]

[[5]]
     [,1]

[[6]]
     [,1]

[[7]]
     [,1]

[[1]]
     [,1]

[[2]]
     [,1]

[[3]]
     [,1]      
[1,] "(we all)"

[[4]]
     [,1]

[[5]]
     [,1]

[[6]]
     [,1]

[[7]]
     [,1]

In [150]:
mat="[0-9]+ (.*)[0-9]+"
# mat="\\(.*\\)"
strs=c('so say 2 or 3 years at colleage and 4 at uni makes us 23 when and if we', 'Mmmm its time 4 me 2 go 2 bed')
str_match_all(string = strs, pattern = mat)

[[1]]
     [,1]                                               
[1,] "2 or 3 years at colleage and 4 at uni makes us 23"
     [,2]                                            
[1,] "or 3 years at colleage and 4 at uni makes us 2"

[[2]]
     [,1]          [,2]      
[1,] "4 me 2 go 2" "me 2 go "

[[1]]
     [,1]                                               
[1,] "2 or 3 years at colleage and 4 at uni makes us 23"
     [,2]                                            
[1,] "or 3 years at colleage and 4 at uni makes us 2"

[[2]]
     [,1]          [,2]      
[1,] "4 me 2 go 2" "me 2 go "

In [151]:
mat="^s(.*)s"
strs=c('studying stuff for the exams')
str_match_all(string = strs, pattern = mat)
mat="^s(.*?)s"
strs=c('studying stuff for the exams')
str_match_all(string = strs, pattern = mat)

[[1]]
     [,1]                           [,2]                        
[1,] "studying stuff for the exams" "tudying stuff for the exam"

[[1]]
     [,1]         [,2]      
[1,] "studying s" "tudying "

[[1]]
     [,1]                           [,2]                        
[1,] "studying stuff for the exams" "tudying stuff for the exam"

[[1]]
     [,1]         [,2]      
[1,] "studying s" "tudying "

In [152]:
#str_wrap(string,width=80,indent=0,exdent=0)
# string	character vector of strings to reformat.
# width	positive integer giving target line width in characters. A width less than or equal to 1 will put each word on its own line.
# indent	non-negative integer giving indentation of first line in each paragraph
# exdent	non-negative integer giving indentation of following lines in each paragraph
thanks_path<-file.path(R.home("doc"),"THANKS")
thanks<-str_c(readLines(thanks_path),collapse = "\n")
thanks
thanks<-word(thanks,1,1,fixed("\n\n"))
thanks
str_wrap(thanks, width=20)
cat(str_wrap(thanks, width=20),"\n")
cat(str_wrap(thanks,width=40),"\n")
cat(str_wrap(thanks,width=60,indent=2),"\n")
cat(str_wrap(thanks,width=60,exdent=2),"\n")

[1] "R would not be what it is today without the invaluable help of these\npeople outside of the R core team, who contributed by donating code, bug\nfixes and documentation:\n\nValerio Aimale, Suharto Anggono, Thomas Baier, Henrik Bengtsson, Roger Bivand,\nBen Bolker, David Brahm, G\"oran Brostr\"om, Patrick Burns, Vince Carey,\nSaikat DebRoy, Matt Dowle, Brian D'Urso, Lyndon Drake, Dirk Eddelbuettel,\nClaus Ekstrom, Sebastian Fischmeister, John Fox, Paul Gilbert,\nYu Gong, Gabor Grothendieck, Frank E Harrell Jr, Peter M. Haverty,\nTorsten Hothorn, Robert King, Kjetil Kjernsmo, Roger Koenker, Philippe Lambert,\nJan de Leeuw, Jim Lindsey, Patrick Lindsey, Catherine Loader,\nGordon Maclean, John Maindonald, David Meyer, Ei-ji Nakama,\nJens Oehlschaegel, Steve Oncley, Richard O'Keefe, Hubert Palme,\nRoger D. Peng, Jose' C. Pinheiro, Tony Plate, Anthony Rossini,\nJonathan Rougier, Petr Savicky, Guenther Sawitzki, Marc Schwartz,\nArun Srinivasan, Detlef Steuer, Bill Simpson, Gordon Smyth, Adrian Trapletti,\nTerry Therneau, Rolf Turner, Bill Venables, Gregory R. Warnes,\nAndreas Weingessel, Morten Welinder, James Wettenhall, Simon Wood, and\nAchim Zeileis.\n\nOthers have written code that has been adopted by R and is\nacknowledged in the code files, including\n\nJ. D. Beasley, David J. Best, Richard Brent, Kevin Buhr, Michael\nA. Covington, Bill Cleveland, Robert Cleveland,, G. W. Cran,\nC. G. Ding, Ulrich Drepper, Paul Eggert, J. O. Evans, David M. Gay,\nH. Frick, G. W. Hill, Richard H. Jones, Eric Grosse, Shelby Haberman,\nBruno Haible, John Hartigan, Andrew Harvey, Trevor Hastie, Min Long\nLam, George Marsaglia, K. J. Martin, Gordon Matzigkeit,\nC. R. Mckenzie, Jean McRae, Cyrus Mehta, Fionn Murtagh, John C. Nash,\nFinbarr O'Sullivan, R. E. Odeh, William Patefield, Nitin Patel, Alan\nRichardson, D. E. Roberts, Patrick Royston, Russell Lenth, Ming-Jen\nShyu, Richard C. Singleton, S. G. Springer, Supoj Sutanthavibul, Irma\nTerpenning, G. E. Thomas, Rob Tibshirani, Wai Wan Tsang, Berwin\nTurlach, Gary V. Vaughan, Michael Wichura, Jingbo Wang, M. A. Wong,\nand the Free Software Foundation (for autoconf code and utilities).\nSee also files under src/extras.\n\nMany more, too numerous to mention here, have contributed by sending bug\nreports and suggesting various improvements.\n\nSimon Davies whilst at the University of Auckland wrote the original\nversion of glm().\n\nJulian Harris and Wing Kwong (Tiki) Wan whilst at the University of\nAuckland assisted Ross Ihaka with the original Macintosh port.\n\nR was inspired by the S environment which has been principally\ndeveloped by John Chambers, with substantial input from Douglas Bates,\nRick Becker, Bill Cleveland, Trevor Hastie, Daryl Pregibon and\nAllan Wilks.\n\nA special debt is owed to John Chambers who has graciously contributed\nadvice and encouragement in the early days of R and later became a\nmember of the core team.\n\n\n\nThe R Foundation may decide to give out <first.lastname>@R-project.org\nemail addresses to contributors to the R Project (even without making them\nmembers of the R Foundation) when in the view of the R Foundation this\nwould help advance the R project.\n\nThe R Core Group, Roger Bivand, Jennifer Bryan, Di Cook, Dirk Eddelbuettel,\nJohn Fox, Bettina Grün, Frank Harrell, Torsten Hothorn, Stefano Iacus,\nJulie Josse, Balasubramanian Narasimhan, Marc Schwartz, Heather Turner,\nBill Venables, Hadley Wickham and Achim Zeileis are the ordinary members of\nthe R Foundation.\nIn addition, David Meyer and Simon Wood are also e-addressable by\n<Firstname>.<Lastname>@R-project.org."

[1] "R would not be what it is today without the invaluable help of these\npeople outside of the R core team, who contributed by donating code, bug\nfixes and documentation:\n\nValerio Aimale, Suharto Anggono, Thomas Baier, Henrik Bengtsson, Roger Bivand,\nBen Bolker, David Brahm, G\"oran Brostr\"om, Patrick Burns, Vince Carey,\nSaikat DebRoy, Matt Dowle, Brian D'Urso, Lyndon Drake, Dirk Eddelbuettel,\nClaus Ekstrom, Sebastian Fischmeister, John Fox, Paul Gilbert,\nYu Gong, Gabor Grothendieck, Frank E Harrell Jr, Peter M. Haverty,\nTorsten Hothorn, Robert King, Kjetil Kjernsmo, Roger Koenker, Philippe Lambert,\nJan de Leeuw, Jim Lindsey, Patrick Lindsey, Catherine Loader,\nGordon Maclean, John Maindonald, David Meyer, Ei-ji Nakama,\nJens Oehlschaegel, Steve Oncley, Richard O'Keefe, Hubert Palme,\nRoger D. Peng, Jose' C. Pinheiro, Tony Plate, Anthony Rossini,\nJonathan Rougier, Petr Savicky, Guenther Sawitzki, Marc Schwartz,\nArun Srinivasan, Detlef Steuer, Bill Simpson, Gordon Smyth, Adrian Trapletti,\nTerry Therneau, Rolf Turner, Bill Venables, Gregory R. Warnes,\nAndreas Weingessel, Morten Welinder, James Wettenhall, Simon Wood, and\nAchim Zeileis.\n\nOthers have written code that has been adopted by R and is\nacknowledged in the code files, including\n\nJ. D. Beasley, David J. Best, Richard Brent, Kevin Buhr, Michael\nA. Covington, Bill Cleveland, Robert Cleveland,, G. W. Cran,\nC. G. Ding, Ulrich Drepper, Paul Eggert, J. O. Evans, David M. Gay,\nH. Frick, G. W. Hill, Richard H. Jones, Eric Grosse, Shelby Haberman,\nBruno Haible, John Hartigan, Andrew Harvey, Trevor Hastie, Min Long\nLam, George Marsaglia, K. J. Martin, Gordon Matzigkeit,\nC. R. Mckenzie, Jean McRae, Cyrus Mehta, Fionn Murtagh, John C. Nash,\nFinbarr O'Sullivan, R. E. Odeh, William Patefield, Nitin Patel, Alan\nRichardson, D. E. Roberts, Patrick Royston, Russell Lenth, Ming-Jen\nShyu, Richard C. Singleton, S. G. Springer, Supoj Sutanthavibul, Irma\nTerpenning, G. E. Thomas, Rob Tibshirani, Wai Wan Tsang, Berwin\nTurlach, Gary V. Vaughan, Michael Wichura, Jingbo Wang, M. A. Wong,\nand the Free Software Foundation (for autoconf code and utilities).\nSee also files under src/extras.\n\nMany more, too numerous to mention here, have contributed by sending bug\nreports and suggesting various improvements.\n\nSimon Davies whilst at the University of Auckland wrote the original\nversion of glm().\n\nJulian Harris and Wing Kwong (Tiki) Wan whilst at the University of\nAuckland assisted Ross Ihaka with the original Macintosh port.\n\nR was inspired by the S environment which has been principally\ndeveloped by John Chambers, with substantial input from Douglas Bates,\nRick Becker, Bill Cleveland, Trevor Hastie, Daryl Pregibon and\nAllan Wilks.\n\nA special debt is owed to John Chambers who has graciously contributed\nadvice and encouragement in the early days of R and later became a\nmember of the core team.\n\n\n\nThe R Foundation may decide to give out <first.lastname>@R-project.org\nemail addresses to contributors to the R Project (even without making them\nmembers of the R Foundation) when in the view of the R Foundation this\nwould help advance the R project.\n\nThe R Core Group, Roger Bivand, Jennifer Bryan, Di Cook, Dirk Eddelbuettel,\nJohn Fox, Bettina Grün, Frank Harrell, Torsten Hothorn, Stefano Iacus,\nJulie Josse, Balasubramanian Narasimhan, Marc Schwartz, Heather Turner,\nBill Venables, Hadley Wickham and Achim Zeileis are the ordinary members of\nthe R Foundation.\nIn addition, David Meyer and Simon Wood are also e-addressable by\n<Firstname>.<Lastname>@R-project.org."

[1] "R would not be what it is today without the invaluable help of these\npeople outside of the R core team, who contributed by donating code, bug\nfixes and documentation:"

[1] "R would not be what it is today without the invaluable help of these\npeople outside of the R core team, who contributed by donating code, bug\nfixes and documentation:"

[1] "R would not be what\nit is today without\nthe invaluable\nhelp of these\npeople outside of\nthe R core team,\nwho contributed\nby donating code,\nbug fixes and\ndocumentation:"

[1] "R would not be what\nit is today without\nthe invaluable\nhelp of these\npeople outside of\nthe R core team,\nwho contributed\nby donating code,\nbug fixes and\ndocumentation:"

R would not be what
it is today without
the invaluable
help of these
people outside of
the R core team,
who contributed
by donating code,
bug fixes and
documentation: 
R would not be what
it is today without
the invaluable
help of these
people outside of
the R core team,
who contributed
by donating code,
bug fixes and
documentation: 
R would not be what it is today
without the invaluable help of these
people outside of the R core team, who
contributed by donating code, bug fixes
and documentation: 
  R would not be what it is today without the invaluable help
of these people outside of the R core team, who contributed
by donating code, bug fixes and documentation: 
R would not be what it is today
without the invaluable help of these
people outside of the R core team, who
contributed by donating code, bug fixes
and documentation: 
  R would not be what it is today without the invaluable help
of these people outside of the R core team, who contributed
by donating code, bug fixes and docu

In [153]:
substr("abcdef", 2, 4)
substr("abcdef", 1:6, 1:6)
substring("abcdef", 1:6, 1:6)
## strsplit is more efficient ...

substr(rep("abcdef", 4), 1:4, 4:5)
x <- c("asfef", "qwerty", "yuiop[", "b", "stuff.blah.yech");x
substr(x, 2, 5)
substring(x, 2, 4:6)

substring(x, 2) <- c("..", "+++")
x

[1] "bcd"

[1] "bcd"

[1] "a"

[1] "a"

[1] "a" "b" "c" "d" "e" "f"

[1] "a" "b" "c" "d" "e" "f"

[1] "abcd" "bcde" "cd"   "de"

[1] "abcd" "bcde" "cd"   "de"

[1] "asfef"           "qwerty"          "yuiop["          "b"              
[5] "stuff.blah.yech"

[1] "asfef"           "qwerty"          "yuiop["          "b"              
[5] "stuff.blah.yech"

[1] "sfef" "wert" "uiop" ""     "tuff"

[1] "sfef" "wert" "uiop" ""     "tuff"

[1] "sfe"   "wert"  "uiop[" ""      "tuff"

[1] "sfe"   "wert"  "uiop[" ""      "tuff"

[1] "a..ef"           "q+++ty"          "y..op["          "b"              
[5] "s..ff.blah.yech"

[1] "a..ef"           "q+++ty"          "y..op["          "b"              
[5] "s..ff.blah.yech"

In [154]:
df = c("abababa aaba aababaa aba a")

In [159]:
regexc("a+(ab)*a+", c)

ERROR: Error in regexc("a+(ab)*a+", c): could not find function "regexc"


ERROR: Error in regexc("a+(ab)*a+", c): could not find function "regexc"


In [160]:
library(tidyverse)

Warning message:
"As of rlang 0.4.0, dplyr must be at least version 0.8.0.
* dplyr 0.7.6 is too old for rlang 0.4.5.
* Please update dplyr to the latest version.
* Updating packages on Windows requires precautions:
  <https://github.com/jennybc/what-they-forgot/issues/62>"
Warning message:
"As of rlang 0.4.0, dplyr must be at least version 0.8.0.
* dplyr 0.7.6 is too old for rlang 0.4.5.
* Please update dplyr to the latest version.
* Updating packages on Windows requires precautions:
  <https://github.com/jennybc/what-they-forgot/issues/62>"
-- Attaching packages --------------------------------------- tidyverse 1.2.1 --

-- Attaching packages --------------------------------------- tidyverse 1.2.1 --

v ggplot2 3.0.0     v readr   1.1.1
v tibble  1.4.2     v purrr   0.3.4
v tidyr   0.8.1     v dplyr   0.7.6
v ggplot2 3.0.0     v forcats 0.3.0

v ggplot2 3.0.0     v readr   1.1.1
v tibble  1.4.2     v purrr   0.3.4
v tidyr   0.8.1     v dplyr   0.7.6
v ggplot2 3.0.0     v forcats 0.3.0

In [162]:

dice = data.frame(c(5,6,3,2,2,4,1),
                c(2,4,3,2,5,6,3),
                c(7,1,5,2,2,6,3),
                c(6,2,3,2,5,1,5),
                c(2,4,1,5,2,6,3),
                c(2,2,4,2,2,2,2))

cols = c('1','2','3','4','5','6')
rows = c('dice1','dice2','dice3','dice4','dice5','dice6','dice7')

colnames(dice) = cols
rownames(dice) = rows


In [163]:
dice

1 2 3 4 5 6
dice1 5 2 7 6 2 2
dice2 6 4 1 2 4 2
dice3 3 3 5 3 1 4
dice4 2 2 2 2 5 2
dice5 2 5 2 5 2 2
dice6 4 6 6 1 6 2
dice7 1 3 3 5 3 2

1 2 3 4 5 6
dice1 5 2 7 6 2 2
dice2 6 4 1 2 4 2
dice3 3 3 5 3 1 4
dice4 2 2 2 2 5 2
dice5 2 5 2 5 2 2
dice6 4 6 6 1 6 2
dice7 1 3 3 5 3 2

In [164]:
df = filter(select(dice, 1, 3, 5), row.names(dice) %in% c("dice3", "dice4"))
df

Warning message:
"`lang()` is deprecated as of rlang 0.2.0.
Please use `call2()` instead.
This warning is displayed once per session."
Warning message:
"`new_overscope()` is deprecated as of rlang 0.2.0.
Please use `new_data_mask()` instead.
This warning is displayed once per session."
Warning message:
"`overscope_eval_next()` is deprecated as of rlang 0.2.0.
Please use `eval_tidy()` with a data mask instead.
This warning is displayed once per session."


1 3 5
1 3 5 1
2 2 2 5

Warning message:
"`lang()` is deprecated as of rlang 0.2.0.
Please use `call2()` instead.
This warning is displayed once per session."
Warning message:
"`new_overscope()` is deprecated as of rlang 0.2.0.
Please use `new_data_mask()` instead.
This warning is displayed once per session."
Warning message:
"`overscope_eval_next()` is deprecated as of rlang 0.2.0.
Please use `eval_tidy()` with a data mask instead.
This warning is displayed once per session."


1 3 5
1 3 5 1
2 2 2 5

In [165]:
dice["total"] = apply(dice, 1, sum)

In [166]:
dice

1 2 3 4 5 6 total
dice1 5 2 7 6 2 2 24   
dice2 6 4 1 2 4 2 19   
dice3 3 3 5 3 1 4 19   
dice4 2 2 2 2 5 2 15   
dice5 2 5 2 5 2 2 18   
dice6 4 6 6 1 6 2 25   
dice7 1 3 3 5 3 2 17

1 2 3 4 5 6 total
dice1 5 2 7 6 2 2 24   
dice2 6 4 1 2 4 2 19   
dice3 3 3 5 3 1 4 19   
dice4 2 2 2 2 5 2 15   
dice5 2 5 2 5 2 2 18   
dice6 4 6 6 1 6 2 25   
dice7 1 3 3 5 3 2 17

In [167]:
df = "abababa aaba aababaa aba a"

In [169]:
str_view(c("abababa", "aaba", "aababaa", "aba","a"), "/a+(ab)*a+/")

HTML widgets cannot be represented in plain text (need html)

HTML widgets cannot be represented in plain text (need html)

In [170]:
str_view(c("abc", "a.c", "a*c", "a c"), "a[ ]")

HTML widgets cannot be represented in plain text (need html)

HTML widgets cannot be represented in plain text (need html)

In [175]:
str_view(c("abababa", "aaba", "aababaa", "aba","a"), "/a+(ab)*a+/")

HTML widgets cannot be represented in plain text (need html)

HTML widgets cannot be represented in plain text (need html)

In [176]:
str_view(c("abcaaaababbbbbcbbbbbbbbb"), "/a*b{2,5}c?/")

HTML widgets cannot be represented in plain text (need html)

HTML widgets cannot be represented in plain text (need html)

In [179]:
str_detect(c("abc", "abcvc", "abcbcbcbc", "ac","aaaaaaaaaa"), "/[abc].c+/")

[1] FALSE FALSE FALSE FALSE FALSE

[1] FALSE FALSE FALSE FALSE FALSE